server:
  port: 9090
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChristianSC8/Examen-BETA.git
          search-paths: config-data
          username: ChristianSC8
          password: @irbusA350
          default-label: main
  security:
    user:
      name: root
      password: Exam3n